### ISSUE TITLE
User couldn't be authenticated, aborting call

### ISSUE THREAD

**Issue by christianhuening** [Terradue/DotNet4One#1]
Hi there,

thanks for this cool lib!

Sadly I am getting a "User couldn't be authenticated, aborting call." error. I tried with oneadmin and the SHA1 hashed PW, as well as with the serveradmin and the security token provided through the Sunstone WebUI. Can you give me a hint what I am doing wrong?

I read something about using the right bindings for the OpenNebula version when using the Java API. Does this apply for this library as well? I am using OpenNebula 4.8.

Cheers,
Christian

**Comment by paranjapeved** [comment]
Hello,
I am experiencing issues in logging in with oneadmin from sunstone. Initially, I when i created a host, it's status would show error. So then i tried a little something. I changed the ssh public/private key which required me to change the password for oneadmin. Now I cannot login with either the old password or the new. Tried all solutions on the internet but to no use. Any help is appreciated.

**Comment by christianhuening** [comment]
Sounds more like a question for the OpenNebula boards, doesn't it?
However I do recall that 'oneadmin' has a password which is generated during installation. So you might not be thought to change it, after all. But not sure about it. Sorry.
