### ISSUE TITLE
Usage Example Problem

### ISSUE THREAD

**Issue by childonline** [Terradue/DotNet4One#4]
I'm trying to run the usage example on top of the virtualbox sandbox provided by opennebula found here: http://opennebula.org/tryout/sandboxvirtualbox/

![image](https://cloud.githubusercontent.com/assets/284391/7260858/f0b41466-e875-11e4-8d5a-942421cc3926.png)

As you can see I've got my VM up and running and working properly on http://localhost:9869/.

However, running:
```
string proxyUrl = "http://localhost:9869/";
string adminUser = "oneadmin";
string adminPwd = "opennebula";
OneClient one = new OneClient(proxyUrl, adminUser, adminPwd);

USER_POOL pool = one.UserGetPoolInfo();
```

fails on line:
```
USER_POOL pool = one.UserGetPoolInfo();
```

with the following error:
![image](https://cloud.githubusercontent.com/assets/284391/7260972/da1bea34-e876-11e4-8e6b-69c00fecd434.png)

I assume `adminUser` and `adminPwd` are incorrect, but these are the only credentials provided.
Any hints why this fails?

Thanks!

**Comment by enguer** [comment]
Indeed, this kind of user and password may not work.
The user should be a user with driver server_* to allow requests delegation and the password should be the SHA1 password.
I recommend to use the user "serveradmin" (should be created by default) and the associated SHA1 password (you can find it doing "oneuser show <id>", <id> being the id of the user).
Let us know if it helps.
Best Regards
The Terradue team

**Comment by childonline** [comment]
I created a new user "admin", assigned it to the oneadmin group (the same group serveradmin is assigned to) and changed its auth_driver to server_* as seen below:
![image](https://cloud.githubusercontent.com/assets/284391/7270989/0e4f8e38-e8e9-11e4-8bac-a8900297342a.png)

Both passwords `admin` and `fe76e79cbc08db8ef3363090fffd5bc718630412` fail with the same exception as before.

I also tried logging with serveradmin but the auth_driver on that is server_cipher.
![image](https://cloud.githubusercontent.com/assets/284391/7271100/c78c0f66-e8e9-11e4-9a85-b094ee4bd976.png)

**Comment by enguer** [comment]
In fact, by server_*, I meant server_cipher ot server_x509.
Did you try to login using "serveradmin" and "c9dff.....660" ?
If yes and it did not work, it means there is another problem to be investigated.
Best Regards
The Terradue team

**Comment by childonline** [comment]
Yes, I din try serveradmin with "c9dff..." :(

**Comment by enguer** [comment]
Another possibility is that the url you use is wrong.
Usually, default XmlRpc urls look like this: http://localhost:2633/RPC2 (cf: http://archives.opennebula.org/documentation:rel4.4:manage_users)
Best Regards
The Terradue team

**Comment by childonline** [comment]
You are absolutley right, I just checked `/etc/one/oned.conf` & the endpoint url should indeed be `http://localhost:2633/RPC2`.
Sunstone also confirms it:
![image](https://cloud.githubusercontent.com/assets/284391/7282575/888d82b8-e939-11e4-92aa-6537b01f3112.png)

So I forwarded port 2633 in VirtualBox, restarted the VM and tried running the following code again:
```
string proxyUrl = "http://localhost:2633/RPC2";
string adminUser = "serveradmin";
string adminPwd = "c9dff2583b47e24c2946419e40dc8ccf6ce0e660";
           
OneClient one = new OneClient(proxyUrl, adminUser, adminPwd);

USER_POOL pool = one.UserGetPoolInfo();
```

However, this time I am greeted with a new exception:
![image](https://cloud.githubusercontent.com/assets/284391/7282817/3309127e-e93b-11e4-92c1-c98a28d905b7.png)

So it seems some progress has been made, but I really don't understand why it fails authentification, I made no changes to `serveradmin`.

**Comment by enguer** [comment]
I think you are not using the good password.
Try to use the one you can find in ~/.one/sunstone_auth
Best Regards
The Terradue team

**Comment by childonline** [comment]
That did the trick! The file was in `/var/lib/one/.one`, but once I found it everything went smoothly.

Thanks alot for helping me out here :beer: !
